import { useEffect, useState } from 'react';
import { Camera, CheckCircle2, ClipboardList, ExternalLink, Plus, X } from 'lucide-react';
import { api, uploadWithProgress } from './api';
import type { CurrentUser, WorkListItemStatus, WorkListOccurrence } from './types';

const labels: Record<string, string> = { DAILY: 'Daily', WEEKLY: 'Weekly · Saturday', MONTHLY: 'Monthly · Last Saturday', OPEN: 'Open', OVERDUE: 'Overdue', SUBMITTED: 'Submitted', SUBMITTED_LATE: 'Submitted late' };

export function WorkListsView({ currentUser, onClose }: { currentUser: CurrentUser; onClose: () => void }) {
  const [lists, setLists] = useState<WorkListOccurrence[]>([]); const [selected, setSelected] = useState<WorkListOccurrence | null>(null); const [error, setError] = useState('');
  const manager = currentUser.roles.some((role) => role === 'ADMINISTRATOR' || role === 'FACILITIES_MANAGER');
  const load = async () => { try { setLists(await api<WorkListOccurrence[]>('/work-lists')); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not load Work Lists.'); } };
  useEffect(() => { void load(); }, []);
  const open = async (item: WorkListOccurrence) => { try { setSelected(await api<WorkListOccurrence>(`/work-lists/${item.id}`)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not load Work List.'); } };
  return <div className="sheet-backdrop"><section className="sheet work-lists-sheet"><header className="sheet-header"><div><span>{manager ? 'Operations activity' : 'Your assigned areas'}</span><h2><ClipboardList /> Work Lists</h2></div><button className="icon-button" onClick={onClose} aria-label="Close"><X /></button></header><div className="sheet-content">{error && <p className="form-error">{error}</p>}{manager && <p className="muted">Managers can review all activity. Templates are managed from the Work Lists settings.</p>}<div className="work-list-cards">{lists.map((list) => <button className={`work-list-card ${list.status.toLowerCase()}`} key={list.id} onClick={() => void open(list)}><span>{labels[list.recurrence]}</span><strong>{list.template_snapshot.title}</strong><p>{list.location_snapshot.name}</p><small>{labels[list.status]} · Due {new Date(list.due_at).toLocaleString()}</small><em>{list.resolved_count ?? 0}/{list.required_count ?? 0} required tasks updated</em></button>)}</div>{!lists.length && <p className="empty-approval">No Work Lists are available yet.</p>}</div>{selected && <WorkListDetail occurrence={selected} manager={manager} onClose={() => setSelected(null)} onChanged={async () => { await load(); setSelected(await api<WorkListOccurrence>(`/work-lists/${selected.id}`)); }} />}</section></div>;
}

function WorkListDetail({ occurrence, manager, onClose, onChanged }: { occurrence: WorkListOccurrence; manager: boolean; onClose: () => void; onChanged: () => Promise<void> }) {
  const [current, setCurrent] = useState(occurrence); const [note, setNote] = useState(occurrence.overall_note ?? ''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const updateItem = async (itemId: string, status: WorkListItemStatus) => { const existing = current.items?.find((item) => item.id === itemId); const reason = status === 'COMPLETED' ? '' : window.prompt(status === 'ISSUE_FOUND' ? 'Describe the issue:' : 'Why is this not applicable?', existing?.note ?? '') ?? ''; if (status !== 'COMPLETED' && reason.trim().length < 3) return; setBusy(true); try { await api(`/work-lists/${current.id}/items/${itemId}`, { method: 'PATCH', body: JSON.stringify({ status, note: reason, expectedVersion: current.version }) }); await onChanged(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not save item.'); } finally { setBusy(false); } };
  const upload = async (file: File) => { setBusy(true); try { const form = new FormData(); form.append('file', file); await uploadWithProgress(`/work-lists/${current.id}/evidence`, form, () => undefined); await onChanged(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Photo upload failed.'); } finally { setBusy(false); } };
  const submit = async () => { setBusy(true); try { await api(`/work-lists/${current.id}/submit`, { method: 'POST', body: JSON.stringify({ note, expectedVersion: current.version }) }); await onChanged(); onClose(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Complete the required tasks and upload a photo before submitting.'); } finally { setBusy(false); } };
  const closed = current.status === 'SUBMITTED' || current.status === 'SUBMITTED_LATE';
  return <div className="drawer-backdrop"><section className="drawer work-list-detail"><header className="drawer-header"><div><span>{labels[current.recurrence]} · {labels[current.status]}</span><h2>{current.template_snapshot.title}</h2><p>{current.location_snapshot.name}</p></div><button className="icon-button" onClick={onClose}><X /></button></header><div className="drawer-content">{current.template_snapshot.instructions && <p className="description">{current.template_snapshot.instructions}</p>}{error && <p className="form-error">{error}</p>}<section className="checklist-items">{current.items?.map((item) => <article key={item.id} className={item.status === 'ISSUE_FOUND' ? 'issue' : ''}><div><strong>{item.title}{item.required && <b> *</b>}</strong>{item.instructions && <p>{item.instructions}</p>}{item.status && <small>{item.status.replaceAll('_', ' ')} {item.resolved_by ? `· ${item.resolved_by}` : ''}{item.note ? ` · ${item.note}` : ''}</small>}</div>{!closed && <div className="item-actions"><button disabled={busy} onClick={() => void updateItem(item.id, 'COMPLETED')}><CheckCircle2 /> Done</button><button disabled={busy} onClick={() => void updateItem(item.id, 'NOT_APPLICABLE')}>N/A</button><button disabled={busy} onClick={() => void updateItem(item.id, 'ISSUE_FOUND')}>Issue</button></div>}</article>)}</section><section className="work-list-evidence"><h3>Completion evidence</h3>{current.evidence?.map((file) => <a key={file.id} href={file.drive_url} target="_blank" rel="noreferrer"><ExternalLink /> {file.file_name} · {file.uploaded_by}</a>)}{!closed && <label className="secondary-button"><Camera /> Add photo<input hidden type="file" accept="image/*" capture="environment" onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(file); }} /></label>}</section>{!closed && <label className="form-field"><span>Overall update *</span><textarea value={note} onChange={(event) => setNote(event.target.value)} minLength={3} placeholder="Briefly describe the completed work or any follow-up." /></label>}</div>{!closed && <footer className="drawer-actions"><button className="primary-button" disabled={busy || note.trim().length < 3} onClick={() => void submit()}>Submit Work List</button></footer>}</section></div>;
}
